### ISSUE TITLE
Typos in english translation

### ISSUE THREAD

**Issue by GvMariani** [betcher/termhelper#1]
While looking at the English files in helps, I noticed some typos:

1. In help.package file, line 3, there is "instllled packages" but it should be "installed packages".
2. In the same file, line 5, there is "without required dependenses", but it should be "without required dependencies".
3. In help.package.build file, line 25, it's used two times the plural "macros", but likely it should say "macro".

**Comment by mikhailnov** [comment]
Fixed, thanks! Feel free to report more problems or send pull requests.
