### ISSUE TITLE
С обновлением dnf перестало предлагать пакеты

### ISSUE THREAD

**Issue by Survolog** [betcher/termhelper#7]
С обновлением dnf на платформе rosa2023.1 дистрибутива Rosa Fresh перестал работать функционал предложения установки пакета.
Потому что команда вида dnf rq -C /usr/bin/foo перестала принимать собственный кеш метадаты:
```
$dnf rq -C /usr/bin/foo
Error: Cache-only enabled but no cache for 'mirror-rosa-x86_64-contrib'
...
```
Хотя проблема, видимо, на стороне dnf, следующая правка чинит работу на стороне termhelper:
https://github.com/betcher/termhelper/blob/52ec8ebab953fa4bc162ee40124feef5f572276c/profile.d/termhelper.sh#L46
```
-		PACKS="$(/usr/bin/dnf repoquery -qC --qf "sudo dnf install %{name}" /usr/bin/$1 /usr/sbin/$1 /bin/$1 /sbin/$1 2>/dev/null)"
+		PACKS="$(/usr/bin/dnf repoquery -qC --qf "sudo dnf install %{name}" $1 2>/dev/null)"
```
Однако, не исследованы последствия.

**Comment by betcher** [comment]
Если выполнить под рутом dnf provides "чего-нибудь" поиск в терминале под пользователем заработает. Раньше достаточно было dnf rerfesh, теперь так. В любом случае чинить здесь нечего.

**Comment by Survolog** [comment]
Закрою тогда.
